name: Build Android APK
on:
  workflow_dispatch: # Allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: mobile-app/package-lock.json

      - name: Install Dependencies
        working-directory: ./mobile-app
        run: npm install
        env:
          CI: true

      - name: Expo Prebuild
        working-directory: ./mobile-app
        run: npx expo prebuild --platform android --no-install --non-interactive

      - name: Verify Android Folder
        working-directory: ./mobile-app
        run: ls -d android || (echo "Android folder not found!" && exit 1)

      - name: Build APK
        working-directory: ./mobile-app/android
        run: |
          chmod +x gradlew
          ./gradlew assembleRelease --stacktrace --info || (tail -n 1000 ../../build_logs.txt && exit 1)

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: mobile-app/android/app/build/outputs/apk/release/*.apk
